/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rizqi mubarrok
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;




public class DashboardForm extends javax.swing.JFrame {

    private void showPanel(JPanel panel) {
    // Hapus panel lama dari area CENTER
    getContentPane().remove(PanelKananDashboard); // jPanel2 adalah panel di sisi kanan (CENTER)

    // Tambahkan panel baru
    PanelKananDashboard = panel; // Ganti jPanel2 dengan panel baru
    getContentPane().add(PanelKananDashboard, java.awt.BorderLayout.CENTER);

    // Refresh tampilan
    revalidate();
    repaint();
}

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        KampanyeButton = new javax.swing.JButton();
        DonasiButton = new javax.swing.JButton();
        PenerimaButton = new javax.swing.JButton();
        DistribusiButton = new javax.swing.JButton();
        PelacakanDanaButton = new javax.swing.JButton();
        DonaturButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        PanelKananDashboard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 670));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 93, 253));
        jLabel14.setText("DONASI");

        jLabel15.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 93, 253));
        jLabel15.setText("KITA");

        KampanyeButton.setBackground(new java.awt.Color(0, 93, 253));
        KampanyeButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        KampanyeButton.setForeground(new java.awt.Color(255, 255, 255));
        KampanyeButton.setText("Kampanye");
        KampanyeButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253))));
        KampanyeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KampanyeButtonActionPerformed(evt);
            }
        });

        DonasiButton.setBackground(new java.awt.Color(0, 93, 253));
        DonasiButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DonasiButton.setForeground(new java.awt.Color(255, 255, 255));
        DonasiButton.setText("Donasi");
        DonasiButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253))));
        DonasiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonasiButtonActionPerformed(evt);
            }
        });

        PenerimaButton.setBackground(new java.awt.Color(0, 93, 253));
        PenerimaButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PenerimaButton.setForeground(new java.awt.Color(255, 255, 255));
        PenerimaButton.setText("Penerima");
        PenerimaButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253))));
        PenerimaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenerimaButtonActionPerformed(evt);
            }
        });

        DistribusiButton.setBackground(new java.awt.Color(0, 93, 253));
        DistribusiButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DistribusiButton.setForeground(new java.awt.Color(255, 255, 255));
        DistribusiButton.setText("Distribusi");
        DistribusiButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253))));
        DistribusiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistribusiButtonActionPerformed(evt);
            }
        });

        PelacakanDanaButton.setBackground(new java.awt.Color(0, 93, 253));
        PelacakanDanaButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PelacakanDanaButton.setForeground(new java.awt.Color(255, 255, 255));
        PelacakanDanaButton.setText("Pelacakan Dana");
        PelacakanDanaButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253))));
        PelacakanDanaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelacakanDanaButtonActionPerformed(evt);
            }
        });

        DonaturButton.setBackground(new java.awt.Color(0, 93, 253));
        DonaturButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DonaturButton.setForeground(new java.awt.Color(255, 255, 255));
        DonaturButton.setText("Donatur");
        DonaturButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253))));
        DonaturButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonaturButtonActionPerformed(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(0, 93, 253));
        LogoutButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Logout");
        LogoutButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253)), javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 93, 253), new java.awt.Color(0, 93, 253))));
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KampanyeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonasiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PenerimaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DistribusiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PelacakanDanaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonaturButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(44, 44, 44)
                .addComponent(PelacakanDanaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(KampanyeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DonasiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PenerimaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DistribusiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DonaturButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        PanelKananDashboard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelKananDashboardLayout = new javax.swing.GroupLayout(PanelKananDashboard);
        PanelKananDashboard.setLayout(PanelKananDashboardLayout);
        PanelKananDashboardLayout.setHorizontalGroup(
            PanelKananDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        PanelKananDashboardLayout.setVerticalGroup(
            PanelKananDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        getContentPane().add(PanelKananDashboard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KampanyeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KampanyeButtonActionPerformed
    showPanel(new KampanyeForm());
    }//GEN-LAST:event_KampanyeButtonActionPerformed

    private void DonasiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonasiButtonActionPerformed
    showPanel(new DonasiForm());        // TODO add your handling code here:
    }//GEN-LAST:event_DonasiButtonActionPerformed

    private void PenerimaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenerimaButtonActionPerformed
    showPanel(new PenerimaForm());         // TODO add your handling code here:
    }//GEN-LAST:event_PenerimaButtonActionPerformed

    private void DistribusiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistribusiButtonActionPerformed
        showPanel(new DistribusiForm()); 
    }//GEN-LAST:event_DistribusiButtonActionPerformed

    private void PelacakanDanaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelacakanDanaButtonActionPerformed
    showPanel(new PelacakanDanaForm());   
    }//GEN-LAST:event_PelacakanDanaButtonActionPerformed

    private void DonaturButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonaturButtonActionPerformed
        showPanel(new DonaturForm()); 
    }//GEN-LAST:event_DonaturButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
    LoginForm dasboard = new LoginForm();
    dasboard.setVisible(true);        // TODO add your handling code here:
    this.dispose();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DistribusiButton;
    private javax.swing.JButton DonasiButton;
    private javax.swing.JButton DonaturButton;
    private javax.swing.JButton KampanyeButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel PanelKananDashboard;
    private javax.swing.JButton PelacakanDanaButton;
    private javax.swing.JButton PenerimaButton;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
